# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockle < Formula
  desc "Simple security auditing, helping build the Best Docker Images"
  homepage "https://github.com/habakke/dockle"
  version "0.3.16"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/habakke/dockle/releases/download/v0.3.16/dockle_0.3.16_macOS-64bit.tar.gz"
      sha256 "331af60c93b81bac3db78db1d15c71c19ce739440744442faedf6bcd5e688df7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/habakke/dockle/releases/download/v0.3.16/dockle_0.3.16_macOS-ARM64.tar.gz"
      sha256 "5e2b84dcac8e98616711f27bddbb961bd40f73bf56fcc543203372c361d40df4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/habakke/dockle/releases/download/v0.3.16/dockle_0.3.16_Linux-64bit.tar.gz"
      sha256 "c2b8ffa456e86dbe74ea0586f5332792ad4aca24c57e8786656074245fa06965"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/habakke/dockle/releases/download/v0.3.16/dockle_0.3.16_Linux-ARM64.tar.gz"
      sha256 "76ce4a552439e067fb9636679b950b8224fc21974c84bfb50097f7787b73852b"
    end
  end

  def install
    bin.install "dockle"
  end

  test do
    system "#{bin}/program --version"
  end
end
